### Usuario 1 (Juan) compra un skin
### Enviado el id, el tipo, el color del skin y el token de autorización
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.uS5QYmvsuNtJ5ai4p1_9CRppeq_lDs2fwStBixDrJV0

{
  "id": 5,
  "type": "Enano",
  "color": "verde"
}

### Usuario 2 (Maria) compra un skin
### Enviado el id, el tipo, el color del skin y el token de autorización
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mn0.9-YCDunjoaKVYYhVaFk8LAL8EsAChVWToIiZpJ8ogCA

{
  "id": 10,
  "type": "Caballero",
  "color": "rojo"
}

### Usuario 3 (Raquel) compra un skin
### Enviado el id, el tipo, el color del skin y el token de autorización
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6M30.MArmGyHMJsYKaDWn5zGoEox6agp0ERRBXa6clb1DfHw

{
  "id": 14,
  "type": "Elfo",
  "color": "oro"
}

### ! ERRORES CONTROLADOS

### Usuario 4 (Ariadna) compra un skin
### Enviado el id, el tipo, el color del skin y el token de autorización
### ! No tiene suficientes coins no la va a poder comprar
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NH0.GcIlSu_3dXzExX46N1jANg_HPSik0guWFMSFopnHRpg

{
  "id": 15,
  "type": "Enano",
  "color": "marron"
}

### ! Usuario no autenticado intenta comprar un skin
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json

{
  "id": 15,
  "type": "Enano",
  "color": "marron"
}

### ! Usuario con un token incorrecto
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.uS5QYmvsuNtJ5ai4p1_9CRppyq_lDs2fwStBixDrJV0

{
  "id": 15,
  "type": "Enano",
  "color": "marron"
}

### Usuario 1 (Juan) compra un skin
### ! Pero envía un body vacio
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.uS5QYmvsuNtJ5ai4p1_9CRppeq_lDs2fwStBixDrJV0

{
  
}

### Usuario 1 (Juan) compra un skin
### ! No envía ni tipo ni color
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.uS5QYmvsuNtJ5ai4p1_9CRppeq_lDs2fwStBixDrJV0

{
  "id": 10
}

### Usuario 1 (Juan) compra un skin
### ! Intenta comprar un skin con un tipo y color no disponibles
POST http://localhost:3001/skins/buy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MX0.uS5QYmvsuNtJ5ai4p1_9CRppeq_lDs2fwStBixDrJV0

{
  "id": 10,
  "type": "Serpiente",
  "color": "Cyan"
}