-- Creamos la DB
DROP DATABASE IF EXISTS skinsdb;
CREATE DATABASE skinsdb DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE skinsdb;

CREATE TABLE skins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  skin_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  class VARCHAR(50) NOT NULL,
  color VARCHAR(50) NOT NULL,
  price INT UNSIGNED NOT NULL
);